#!/usr/bin/env zsh

# NVIM 
ln -s $(pwd)/nvim/.config/nvim ~/.config/nvim

# TMUX
ln -s $(pwd)/tmux/.tmux.conf ~/.tmux.conf

# ZSH
ln -s $(pwd)/zsh/.aliases ~/.aliases
ln -s $(pwd)/zsh/.autocomplete.zsh ~/.autocomplete.zsh
ln -s $(pwd)/zsh/.zsh_profile ~/.zsh_profile

ln -s $(pwd)/bin/.local/scripts ~/.local/scripts
